const model = {
    //app
    curentPage: 'game',
    colorToMove: 'white',
    lastMovedPieceIndex: 0,
    modal: 'none',
    currentIndexOfWhiteKing: 32,
    whiteIsInCheck: false,
    currentIndexOfBlackKing: 39,
    blackIsInCheck: false,

    //inputs
    inputs:
    {
        pieceIsPrimed: false,
        showSquareId: false,
        blackColor: '#800000',
        whiteColor: '#ffffff',
        currentlyMovingPiece: '',
    },
    //data
    legalMoveSquareColor: '#808080',
    arrayLeters: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
    arrayNumbers: ['1', '2', '3', '4', '5', '6', '7', '8',],
    selectedColorBlack: '#800000',
    selectedColorWhite: 'ffffff',
    board: [],
    promoteBlackImg: [
        'img/black queen.png',
        'img/black rook.png',
        'img/black bishop.png',
        'img/black horse.png',
    ],
    promoteWhiteImg: [
        'img/white queen.png',
        'img/white rook.png',
        'img/white bishop.png',
        'img/white horse.png',
    ],
    allInPlayPieces: [
        {
            id: 'black king e',
            possison: 'e8',
            color: 'black',
            hasMoved: false,
            imageLink: 'img/black king.png',
        },
        {
            id: 'black queen d',
            possison: 'd8',
            color: 'black',
            imageLink: 'img/black queen.png',
        },
        {
            id: 'black bishop c',
            possison: 'c8',
            color: 'black',
            imageLink: 'img/black bishop.png',
        },
        {
            id: 'black bishop f',
            possison: 'f8',
            color: 'black',
            imageLink: 'img/black bishop.png',
        },
        {
            id: 'black horse b',
            possison: 'b8',
            color: 'black',
            imageLink: 'img/black horse.png',
        },
        {
            id: 'black horse g',
            possison: 'g8',
            color: 'black',
            imageLink: 'img/black horse.png',
        },
        {
            id: 'black rook a',
            possison: 'a8',
            color: 'black',
            hasMoved: false,
            imageLink: 'img/black rook.png',
        },
        {
            id: 'black rook h',
            possison: 'h8',
            color: 'black',
            hasMoved: false,
            imageLink: 'img/black rook.png',
        },
        {
            id: 'black pawn a',
            possison: 'a7',
            color: 'black',
            hasMoved: false,
            imageLink: 'img/black pawn.png',
        },
        {
            id: 'black pawn b',
            possison: 'b7',
            color: 'black',
            hasMoved: false,
            imageLink: 'img/black pawn.png',
        },
        {
            id: 'black pawn c',
            possison: 'c7',
            color: 'black',
            hasMoved: false,
            imageLink: 'img/black pawn.png',
        },
        {
            id: 'black pawn d',
            possison: 'd7',
            color: 'black',
            hasMoved: false,
            imageLink: 'img/black pawn.png',
        },
        {
            id: 'black pawn e',
            possison: 'e7',
            color: 'black',
            hasMoved: false,
            imageLink: 'img/black pawn.png',
        },
        {
            id: 'black pawn f',
            possison: 'f7',
            color: 'black',
            hasMoved: false,
            imageLink: 'img/black pawn.png',
        },
        {
            id: 'black pawn g',
            possison: 'g7',
            color: 'black',
            hasMoved: false,
            imageLink: 'img/black pawn.png',
        },
        {
            id: 'black pawn h',
            possison: 'h7',
            color: 'black',
            hasMoved: false,
            imageLink: 'img/black pawn.png',
        },
        {
            id: 'white king e',
            possison: 'e1',
            color: 'white',
            hasMoved: false,
            imageLink: 'img/white king.png',
        },
        {
            id: 'white queen d',
            possison: 'd1',
            color: 'white',
            imageLink: 'img/white queen.png',
        },
        {
            id: 'white bishop c',
            possison: 'c1',
            color: 'white',
            imageLink: 'img/white bishop.png',
        },
        {
            id: 'white bishop f',
            possison: 'f1',
            color: 'white',
            imageLink: 'img/white bishop.png',
        },
        {
            id: 'white horse b',
            possison: 'b1',
            color: 'white',
            imageLink: 'img/white horse.png',
        },
        {
            id: 'white horse g',
            possison: 'g1',
            color: 'white',
            imageLink: 'img/white horse.png',
        },
        {
            id: 'white rook a',
            possison: 'a1',
            color: 'white',
            hasMoved: false,
            imageLink: 'img/white rook.png',
        },
        {
            id: 'white rook h',
            possison: 'h1',
            color: 'white',
            hasMoved: false,
            imageLink: 'img/white rook.png',
        },
        {
            id: 'white pawn a',
            possison: 'a2',
            color: 'white',
            hasMoved: false,
            imageLink: 'img/white pawn.png',
        },
        {
            id: 'white pawn b',
            possison: 'b2',
            color: 'white',
            hasMoved: false,
            imageLink: 'img/white pawn.png',
        },
        {
            id: 'white pawn c',
            possison: 'c2',
            color: 'white',
            hasMoved: false,
            imageLink: 'img/white pawn.png',
        },
        {
            id: 'white pawn d',
            possison: 'd2',
            color: 'white',
            hasMoved: false,
            imageLink: 'img/white pawn.png',
        },
        {
            id: 'white pawn e',
            possison: 'e2',
            color: 'white',
            hasMoved: false,
            imageLink: 'img/white pawn.png',
        },
        {
            id: 'white pawn f',
            possison: 'f2',
            color: 'white',
            hasMoved: false,
            imageLink: 'img/white pawn.png',
        },
        {
            id: 'white pawn g',
            possison: 'g2',
            color: 'white',
            hasMoved: false,
            imageLink: 'img/white pawn.png',
        },
        {
            id: 'white pawn h',
            possison: 'h2',
            color: 'white',
            hasMoved: false,
            imageLink: 'img/white pawn.png',
        },

    ],

}